spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: movies
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
server:
  error:
    path: /error